apps/employees/urls.py
from django.urls import path

from apps.prova_vida.views import export_to_excel_faltoso

from .views import (
    DownloadCSVViewdownloadcsv,
    EmployeeBulkUploadView,
    EmployeeCreateView,
    EmployeeDeleteView,
    EmployeeDetailView,
    EmployeeListView,
    EmployeeUpdateView,
    employee_detail,
    employee_edit,   
    employee_list,
    addFuncionario,
    editFuncionario,
    upload_excel,
    gerarPDF,
    gerarLicenciadosPDF,
    gerarPreReformaPDF,
    deleteFuncionario,
    employee_delete,
    get_employee_report,
    employee_list_type,
    employee_list_pv,
    employee_list_ajax,
    export_to_excel,
    export_to_excel_licenciados,
    export_to_excel_pre_reformados,
    
    
     
)

urlpatterns = [
    path("list", employee_list, name="employee-list"),
    path("employee-list-ajax/<int:page>", employee_list_ajax, name="employee-list-ajax"),

    path("employee-list-type/<str:tipo>", employee_list_type, name="employee-list-type"),
    path("employee-detail/<int:id>", employee_detail, name="employee-detail"),
    path("employee-edit/<int:id>",employee_edit, name="employee-edit"),
    path("employee-delete/<int:id>",employee_delete, name="employee-delete"),
    path("create/", addFuncionario, name="employee-create"),
    path("update/",editFuncionario, name="employee-update"),
    path("delete/", deleteFuncionario, name="employee-delete"),
    #path("upload/", EmployeeBulkUploadView.as_view(), name="employee-upload"),
    path('upload/', upload_excel, name='upload_excel'),
    path("download-csv/", DownloadCSVViewdownloadcsv.as_view(), name="download-csv"),

    path("funcionario-pdf", gerarPDF, name="funcionario-pdf"),
    path("funcionario-licenciado-pdf", gerarLicenciadosPDF, name="funcionario-licenciado-pdf"),
    path("funcionario-pre-reforma-pdf", gerarPreReformaPDF, name="funcionario-pre-reforma-pdf"),
    path("funcionario-relatorio", get_employee_report, name="funcionario-relatorio"),

    path("employee-list-pv/<str:tipo>", employee_list_pv, name="employee-list-pv"),
 
    path('export_to_excel_funcionarios', export_to_excel, name='export-excel-funcionarios'),
    path('export_to_excel_funcionarios-licenciados', export_to_excel_licenciados, name='export-excel-funcionarios-licenciados'),
    path('export_to_excel_funcionarios-pre-reforma', export_to_excel_pre_reformados, name='export-excel-funcionarios-pre-reforma'),
    path('export_to_excel_funcionarios_faltosos', export_to_excel_faltoso, name='export-excel-funcionarios-faltosos'),
]

hrm_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path('admin/', admin.site.urls),
#    path("finance/", include("apps.finance.urls")),
#    path("result/", include("apps.result.urls")),
    path("employee/", include("apps.employees.urls")),
    #path("abertura_prova_vida/", include("apps.abertura_prova_vida.urls")),
    path("prova_vida/", include("apps.prova_vida.urls")),
    path("doc/", include("apps.docs.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/employees/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
import hrm_app.settings as sett
import uuid

from apps.corecode.models import (
    DireccaoDepartamento,
    Estacao,
    PermitDocCategory,
    Citizenship,
    DirecaoAlocacao,
    Categoria,
    CategoriaNova,
    FuncaoChefia,
)


class Estabelecimento(models.Model):
    nome = models.CharField(max_length=200, verbose_name="Nome do Estabelecimento")





class Employee(models.Model):
    STATUS_CHOICES = [
        ("activo", "Activo"),
        ("pre-reformado", "Pré-Reformado"),
        ("licenciado", "Licenciado"),
        ("reformado", "Reformado"),
    ]
    ESTADO = [("activo", "Activo"), ("inactivo", "Inactivo"), ("incluso", "Incluso")]
    ORIGEM = [("primavera", "Primavera"), ("incluso", "Incluso")]

    ESTADO_OBJECTO = [("activo", "Activo"), ("eliminado", "Eliminado")]

    ESTADO_PV = [("pendente", "Pendente"), ("feito", "Feito"), ("faltoso", "Faltoso")]
    ESTADO_CIVIL = [
        ("solteiro", "Solteiro(a)"),
        ("casado", "Casado(a)"),
        ("divorciado", "Divorciado(a)"),
        ("viuvo", "Viúvo(a)"),
    ]
    PROVINCIAS = [
        ("Bengo", "Bengo"),
        ("Benguela", "Benguela"),
        ("Bié", "Bié"),
        ("Cabinda", "Cabinda"),
        ("Cuando Cubango", "Cuando Cubango"),
        ("Cuanza Norte", "Cuanza Norte"),
        ("Cuanza Sul", "Cuanza Sul"),
        ("Cunene", "Cunene"),
        ("Huambo", "Huambo"),
        ("Huíla", "Huíla"),
        ("Luanda", "Luanda"),
        ("Lunda Norte", "Lunda Norte"),
        ("Lunda Sul", "Lunda Sul"),
        ("Malanje", "Malanje"),
        ("Moxico", "Moxico"),
        ("Namibe", "Namibe"),
        ("Uíge", "Uíge"),
        ("Zaire", "Zaire"),
    ]

    GENDER_CHOICES = [("masculino", "Мasculino"), ("femenino", "Femenino")]
    TIPO_REFORMA = [
        ("reformado", "Reformado"),
        ("pré-reforma", "Pré-reforma"),
        ("não reformado", "Não reformado"),
    ]

    current_status = models.CharField(
        max_length=100,
        choices=STATUS_CHOICES,
        default="activo",
        verbose_name="situacao",
    )
    estado = models.CharField(
        max_length=100, choices=ESTADO, default="activo", verbose_name="estado"
    )
    origem = models.CharField(
        max_length=100, choices=ORIGEM, default="incluso", verbose_name="origem"
    )
    personnel_number = models.CharField(
        max_length=2000, unique=True, verbose_name="Número do BI", null=True
    )
    data_de_emissao = models.DateField(
        blank=True, null=True, verbose_name="Data de Emissão do BI"
    )
    data_de_validade = models.DateField(
        blank=True, null=True, verbose_name="Data de Validade do BI"
    )
    numero_mecanografico = models.CharField(
        max_length=2000, unique=True, verbose_name="Número Mecanográfico", null=True
    )
    firstname = models.CharField(max_length=2000, verbose_name="Primeiro Nome")
    surname = models.CharField(max_length=2000, verbose_name="SobreNome")
    idade = models.CharField(max_length=2000, verbose_name="Idade")
    correio_electronico = models.CharField(
        max_length=2000, verbose_name="Correio Electrónico", null=True
    )
    gender = models.CharField(
        max_length=10,
        choices=GENDER_CHOICES,
        default="masculino",
        verbose_name="Genero",
    )
    date_of_birth = models.DateField(
        blank=True, null=True, verbose_name="Data de Nascimento"
    )
    provincia_residencia = models.CharField(
        max_length=30,
        choices=PROVINCIAS,
        default="Luanda",
        verbose_name="Província de Residência",
    )
    provincia_nascimento = models.CharField(
        max_length=30,
        choices=PROVINCIAS,
        default="Luanda",
        verbose_name="Província de Nascimento",
    )
    naturalidade = models.CharField(
        max_length=30, verbose_name="Naturalidade", null=True
    )
    estado_civil = models.CharField(
        max_length=20,
        choices=ESTADO_CIVIL,
        default="solteiro",
        verbose_name="Estado Cívil",
    )
    localidade = models.CharField(max_length=2000, verbose_name="Localidade", null=True)
    morada = models.CharField(max_length=2000, verbose_name="Morada", null=True)
    numero_dependentes = models.CharField(
        max_length=2000, verbose_name="Número Dependentes", null=True
    )
    telefone = models.CharField(max_length=9, verbose_name="Telefone", null=True)
    habilitacao = models.CharField(
        max_length=2000, verbose_name="Habilitação", null=True
    )
    area_de_formacao = models.CharField(
        max_length=2000, verbose_name="Área de Formação", null=True
    )
    vencimento_mensal = models.CharField(
        max_length=9, verbose_name="Vencimento", null=True
    )
    # numero_inss = models.CharField(max_length=200, unique=True, verbose_name="Número INSS",null=True)

    reforma = models.CharField(
        max_length=20, choices=TIPO_REFORMA, default="reformado", verbose_name="Reforma"
    )
    tempo_na_empresa = models.CharField(max_length=50, default="NaN")

    data_de_admissao = models.DateField(
        blank=True, null=True, verbose_name="Data de Admissão"
    )

    direccao = models.ForeignKey(
        DirecaoAlocacao,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Direção de Alocação",
    )
    
    direccaoDepart = models.ForeignKey(
        DireccaoDepartamento,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Departamento ou Direcção",
    )
    estacao = models.ForeignKey(
        Estacao,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Estacão",
    )
    # nacionalidade = models.ForeignKey(
    #     Citizenship,
    #     on_delete=models.CASCADE,
    #     blank=True,
    #     null=True,
    #     verbose_name="Nacionalidade",
    # )
    nacionalidade = models.CharField(max_length=50, default="NaN")

    categoria_laboral_antiga = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Categoria Antiga",
         related_name="funcionarios_com_categoria_antiga"
    )

    categoria_laboral_nova = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Categoria Nova",
         related_name="funcionarios_com_categoria_nova"
    )

    data_de_admissao = models.DateField(verbose_name="Data de Demissão", null=True)

    # numero_telefone = models.CharField(
    #    max_length=9, blank=True, verbose_name="Numero de
    # "
    # )

    vinculo_professor = models.CharField(
        max_length=2000, verbose_name="Vinculo Professor", null=True
    )
    curso_ministrado = models.CharField(
        max_length=2000, verbose_name="Curso Ministrado", null=True
    )
    regime_trabalho = models.CharField(
        max_length=2000, verbose_name="Regime Trabalho", null=True
    )

    vinculo_administrativo = models.CharField(
        max_length=2000, verbose_name="Vinculo Administrativo", null=True
    )
    data_de_admissao_administrativo = models.DateField(
        blank=True, null=True, verbose_name="Data de Admissão Administrativo"
    )

    # direccao_administrativo = models.CharField(
    #     max_length=2000, blank=True, null=True, verbose_name="Direção de Alocação Administrativo"
    # )
    # categoria_laboral_administrativo = models.CharField(
    #     max_length=2000, blank=True, null=True, verbose_name="Categoria"
    # )
    # funcao_chefia_administrativo = models.CharField(
    #     max_length=2000, blank=True, null=True, verbose_name="Função de Chefia Administrativo"
    # )

    categoria_laboral_administrativo = models.CharField(
        max_length=2000, blank=True, null=True
    )
    funcao_chefia_administrativo = models.CharField(
        max_length=2000, blank=True, null=True
    )
    direccao_administrativo = models.CharField(max_length=2000, blank=True, null=True)

    def set_categoria_laboral_administrativo(self, categoria):
        self.categoria_laboral_administrativo = str(categoria.id)

    def set_funcao_chefia_administrativo(self, funcao_chefia):
        self.funcao_chefia_administrativo = str(funcao_chefia.id)

    def set_direccao_administrativo(self, direcao):
        self.direccao_administrativo = str(direcao.id)

    vencimento_mensal_administrativo = models.CharField(
        max_length=9, verbose_name="Vencimento Administrativo", null=True
    )

    habilitacao_administrativo = models.CharField(
        max_length=2000, verbose_name="Habilitação", null=True
    )
    area_de_formacao_administrativo = models.CharField(
        max_length=2000, verbose_name="Área de Formação", null=True
    )
    regime_trabalho_administrativo = models.CharField(
        max_length=2000, verbose_name="Regime Trabalho Administrativo", null=True
    )

    profissao = models.CharField(max_length=2000, verbose_name="Profissão", null=True)
    tipo_contrato = models.CharField(
        max_length=2000, verbose_name="Tipo de Contrato", null=True
    )
    tipo_pessoal = models.CharField(
        max_length=2000, verbose_name="Tipo de Pessoal", null=True
    )
    motivo_admissao = models.CharField(
        max_length=2000, verbose_name="Motivo Admissão", null=True
    )
    data_de_demissao = models.DateField(
        blank=True, null=True, verbose_name="Data de Demissão"
    )
    motivo_demissao = models.CharField(
        max_length=2000, verbose_name="Motivo Demissao", null=True
    )

    data_fim_contrato = models.DateField(
        blank=True, null=True, verbose_name="Data de Fim de Contrato"
    )
    anos_trabalho = models.CharField(
        max_length=2000, verbose_name="Anos de Trabalho", null=True
    )
    cargo = models.CharField(max_length=2000, verbose_name="Cargo / Função", null=True)

apps/employees/forms.py
from django import forms
from django.forms import ModelForm
import hrm_app.settings as sett
from django.db import models

from .models import (
    Employee
)


class EmployeeForm(ModelForm):
    prefix = "Employee"
    # date_of_birth = DateTimeField(input_formats=sett.DATE_INPUT_FORMATS)
    class Meta:
        model = Employee
        exclude = ["current_status"]


from django import forms

class ExcelUploadForm(forms.Form):
    excel_file = forms.FileField()

apps/employees/templates/employees/categoria_nova_success.html
{% extends 'base.html' %}
{% load static %}



{% block main %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Nova Categoria Profissional
        <small>RH</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'home' %}"><i class="fa fa-dashboard"></i> Página Inicial</a></li>
        <li><a href="#">Recursos Humanos</a></li>
        <li class="active"> <a> Nova Categoria Profissional <small class="label pull-right" style="color: green;">
              <font style="vertical-align: inherit;">
                <font style="vertical-align: inherit;">Geral</font>
              </font>
            </small> </a></li>
      </ol>
    </section>
    <br>
    <div class="col-md-12">
      <div class="box box-success ">
        <div class="box-header with-border" style="height: 70px">
          <h5 class="box-title" style="font-size: 12px"><i class="fa fa-fw  fa-object-group"></i> Recursos Humanos
          </h5>

          <div class="box-tools pull-right">

            <div class="alert text-white bg-success" style="padding-right: 6px;" role="alert">
              <div class="iq-alert-text">Nova Categoria Profissional Cadastrada com Sucesso!</div>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <i class="ri-close-line"></i>
              </button>
           </div> 
            &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
            <img src="{% static 'imagens/bwcangola_logo.png' %}" style="width: 70px; height:2%">
          </div>
          <br>
          <p></p>
        </div>
      </div>
    </div>

    <section class="content">
      <!-- Page Content  -->
      <div class="row">
        <div class="col-md-12">
          <div class="iq-card">
            <div class="iq-card-header d-flex justify-content-between">
              <div class="iq-header-title">
                <br>
                <h4 class="card-title">Resumo Cadastro da Nova Categoria Profissional</h4>
                <span>
                  
                </span>
                
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="">

                  <div class="-header d-flex justify-content-between">
                    <br>

                  </div>
                  <div class="-body" style="padding-left: 0;">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="">
      
                          <div class="-header d-flex justify-content-between">
                 
      
                          </div>
                          <div class="iq-card-body" style="padding-left: 0;">
                            <div class="row"> 
                               <div class="col-md-8">
                                  <form id="form-wizard3" class="text-center">
                                     <!-- fieldsets -->
                                     <fieldset>
                                        <div class="form-card text-left">
                                           <div class="row">
                                           </div>
                                           <div class="form-card text-left">
                                            <div class="row">
                                              <div class="col-12">
                                              </div>
                                            </div>
                                            <div class="row">
                                              <div class="col-md-1">
                                                  
                                              </div>
                                              <div class="col-md-11">
                                                <form id="form-wizard3" class="text-center">
                                                   <!-- fieldsets -->
                                                   <fieldset>
                                                      <div class="form-card text-left">
                                                         <div class="row">
                                                            <div class="col-12">
                                                               <h3 class="mb-4"><i class="fa fa-address-card"></i> Informações:</h3>
                                                               <br>
                                                            </div>
                                                         </div>
                                                         <div class="form-card text-left">
                                                          <div class="row">
                                                            <div class="col-12">
                                                              <!-- <h4 class="mb-4">Informações Pessoais:</h4> -->
                                                            </div>
                                                          </div>
                                                          <div class="row">
                                                            <div class="col-md-12">
                                                              <div class="form-group">
                                                                <h5>Nome da Categoria Profissional:</h5>
                                                                <label class="control-label">{{categoria_nova}}</label>
                                                              </div>
                                                            </div>
                                                   </fieldset>
                                                   <a href="{% url 'home' %}" type="button" name="previous" class="btn btn-primary previous action-button-previous pull-right " value="Previous" style="margin-right: 3px;">Página Inicial</a>
                                                </form>
                                             </div>
                                     </fieldset>
                                  </form>
                                  
                               </div>
                            </div>
                         </div>
                        </div>
                      </div>
                    </div>
                    <br>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
  </div>

  </section>
  <!-- /.content -->
  </div>

  {% endblock main %}

apps/employees/templates/employees/departamento_success.html
{% extends 'base.html' %}
{% load static %}



{% block main %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Departamento
        <small>RH</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{% url 'home' %}"><i class="fa fa-dashboard"></i> Página Inicial</a></li>
        <li><a href="#">Recursos Humanos</a></li>
        <li class="active"> <a> Departamento <small class="label pull-right" style="color: green;">
              <font style="vertical-align: inherit;">
                <font style="vertical-align: inherit;">Geral</font>
              </font>
            </small> </a></li>
      </ol>
    </section>
    <br>
    <div class="col-md-12">
      <div class="box box-success ">
        <div class="box-header with-border" style="height: 70px">
          <h5 class="box-title" style="font-size: 12px"><i class="fa fa-fw  fa-object-group"></i> Recursos Humanos
          </h5>

          <div class="box-tools pull-right">

            <div class="alert text-white bg-success" style="padding-right: 6px;" role="alert">
              <div class="iq-alert-text">Departamento Cadastrado com Sucesso!</div>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <i class="ri-close-line"></i>
              </button>
           </div> 
            &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
            <img src="{% static 'imagens/bwcangola_logo.png' %}" style="width: 70px; height:2%">
          </div>
          <br>
          <p></p>
        </div>
      </div>
    </div>

    <section class="content">
      <!-- Page Content  -->
      <div class="row">
        <div class="col-md-12">
          <div class="iq-card">
            <div class="iq-card-header d-flex justify-content-between">
              <div class="iq-header-title">
                <br>
                <h4 class="card-title">Resumo Cadastro do Departamento</h4>
                <span>
                  
                </span>
                
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="">

                  <div class="-header d-flex justify-content-between">
                    <br>

                  </div>
                  <div class="-body" style="padding-left: 0;">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="">
      
                          <div class="-header d-flex justify-content-between">
                 
      
                          </div>
                          <div class="iq-card-body" style="padding-left: 0;">
                            <div class="row"> 
                               <div class="col-md-8">
                                  <form id="form-wizard3" class="text-center">
                                     <!-- fieldsets -->
                                     <fieldset>
                                        <div class="form-card text-left">
                                           <div class="row">
                                           </div>
                                           <div class="form-card text-left">
                                            <div class="row">
                                              <div class="col-12">
                                              </div>
                                            </div>
                                            <div class="row">
                                              <div class="col-md-1">
                                                  
                                              </div>
                                              <div class="col-md-11">
                                                <form id="form-wizard3" class="text-center">
                                                   <!-- fieldsets -->
                                                   <fieldset>
                                                      <div class="form-card text-left">
                                                         <div class="row">
                                                            <div class="col-12">
                                                               <h3 class="mb-4"><i class="fa fa-address-card"></i> Informações:</h3>
                                                               <br>
                                                            </div>
                                                         </div>
                                                         <div class="form-card text-left">
                                                          <div class="row">
                                                            <div class="col-12">
                                                              <!-- <h4 class="mb-4">Informações Pessoais:</h4> -->
                                                            </div>
                                                          </div>
                                                          <div class="row">
                                                            <div class="col-md-12">
                                                              <div class="form-group">
                                                                <h5>Nome do Departamento:</h5>
                                                                <label class="control-label">{{departamento.nome}}</label>
                                                              </div>
                                                            </div>
                                                   </fieldset>
                                                   <a href="{% url 'home' %}" type="button" name="previous" class="btn btn-primary previous action-button-previous pull-right " value="Previous" style="margin-right: 3px;">Página Inicial</a>
                                                </form>
                                             </div>
                                     </fieldset>
                                  </form>
                                  
                               </div>
                            </div>
                         </div>
                        </div>
                      </div>
                    </div>
                    <br>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
  </div>

  </section>
  <!-- /.content -->
  </div>

  {% endblock main %}

apps/employees/templates/employees/employee_detail copy.html
{% extends 'base.html' %}
{% load static %}

{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool">Распечатать</a>
    <a href="{% url 'employee-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'employee-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
    <div class="row mb-4">
      <div class="col-sm-4">
        <div class="row mb-2">

          {% if object.passport %}
            <img
              src="{{ object.passport.url }}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% else %}
            <img
              src="{% static 'dist/img/avatar.png' %}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% endif %}


          <div class="float-right">
            <h4>{{ object.surname }} </h4>
            <h4>{{ object.firstname }} </h4>
            <h4>{{ object.other_name }} </h4>
            <h4>{{ object.registration_number }} </h4>
          </div>
        </div>
        <h5>{{ object.current_class }} </h5>
        <h5>{{ object.get_gender_display }} | {{ object.get_current_status_display }}</h5>

      </div>
      <div class="col-sm-8">
        <div>
          <div class="form-group border-bottom row">
            <label class="col">
              Дата рождения
            </label>
            <div class="col">
              {{ object.date_of_birth }}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Тел номер
            </label>
            <div class="col">
              {{ object.parent_mobile_number}}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Адрес
            </label>
            <div class="col">
              {{ object.address }}
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Комментарий
            </label>
            <div class="col">
              {{ object.others }}
            </div>
          </div>

        </div>

      </div>
    </div>

    <h4>Invoice/Payment History</h4>
    {% if payments %}
      <table class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>For</th>
            <th>Amount Payable</th>
            <th>Amount Paid</th>
            <th>balance</th>
          </tr>
        </thead>
        <tbody>
          {% for payment in payments %}
            <tr class='clickable-row' data-href="{% url 'invoice-detail' payment.id %}">
              <td>{{payment.session}} - {{payment.term}} - {{ payment.class_for}}</td>
              <td>{{payment.total_amount_payable}}</td>
              <td>{{payment.total_amount_paid}}</td>
              <td>{{payment.balance}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
        <p>There are no payment history for {{object}}</p>
    {% endif %}




{% endblock content %}

apps/employees/templates/employees/employee_form_old.html
{% extends 'base.html' %}
{% load static %}


{% block title %}

  {% if object %}
    Actualizar {{ object }}
  {% else %}
  Adicionar um novo funcionário
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  {% include 'corecode/form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Atualizar entrada">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Adicionar um novo funcionário">
  {% endif %}
</form> 


{% endblock content %}

apps/employees/templates/employees/employee_funcao_chefia.html
{% extends 'base.html' %}
{% load static %}


{% block main %}



{% endblock main %}

apps/employees/templates/employees/upload.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Excel File</title>
</head>
<body>
    <h2>Upload Excel File</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>